version: "3.8"

services:
  api:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      API_URL: ${API_URL}
      DB_URL: ${DB_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - net

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    networks:
      - net
    healthcheck:
      test: pg_isready -d ${DB_URL}
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  net:
